# Generated by Django 6.0.6 on 2026-06-13 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='news/covers/', verbose_name='Image de couverture')),
                ('excerpt', models.TextField(blank=True, verbose_name='Résumé')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('document', models.FileField(blank=True, null=True, upload_to='news/documents/', verbose_name='Document PDF')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publié')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/', verbose_name='Image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='news.news', verbose_name='Actualité')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Galerie Photos',
            },
        ),
        migrations.CreateModel(
            name='NewsVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre vidéo')),
                ('youtube_url', models.URLField(verbose_name='Lien YouTube')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='news.news', verbose_name='Actualité')),
            ],
            options={
                'verbose_name': 'Vidéo',
                'verbose_name_plural': 'Vidéos',
            },
        ),
    ]
